---
# Main
username: "{{ ansible_env.USER }}"
email: "{{ username }}@es.net"
hostname: "{{ username }}-mbp"
home_dir: "/Users/{{ username }}"

# apps
cask_apps:
  - slack
  - visual-studio-code
  - microsoft-remote-desktop
  - google-chrome
  - google-drive
  - keepassx
  - iterm2
  - docker
  - virtualbox

formula_apps:
  - tree
  - neofetch
  - jq
  - python
  - nmap
  - trippy

# Zsh
login_shell: "/usr/local/bin/zsh"
custom_plugin_source_path: "/Users/gstewart/Google\ Drive/My\ Drive/code/bash/oh-my-zsh-custom"
local_projects_path: "~/repos"
dotfiles_repo: "git@github.com:gstewart86/dotfiles.git"
zsh_plugins:
  - git
  - virtualenv
  - python
  - brew
  - docker
  - ansible

additional_plugins:
  - name: zsh-docker-aliases
    repo: "git@github.com:akarzim/zsh-docker-aliases.git"

zsh_themes:
  - name: powerlevel10k
    repo: 'https://github.com/romkatv/powerlevel10k.git'

# OSX_Base
ssh_source_path: "/Users/gstewart/Google\ Drive/My\ Drive/keys/id_rsa"
ssh_key_name: "{{ ssh_dir }}/id_rsa"

# Tweaks
finder_new_window_path: "file://{{ home_dir }}"
screenshots_dir: "{{ home_dir }}/Downloads"
dockitems_remove_all: true

dockutil_desired:
  - name: System Preferences
    path: "/Applications/System Preferences.app"
    pos: 6

dockutil_desired_right:
  - name: Applications
    path: '/Applications'
    pos: 7
    view: auto
    display: stack
    sort: name
    section: others
  - name: Utilities
    path: '/Applications/Utilities'
    pos: 9
    view: auto
    display: stack
    sort: name
    section: others
  - name: Home
    path: '/Users/{{ username }}'
    pos: 10
    view: auto
    display: folder
    sort: name
    section: others
  - name: Downloads
    path: '/Users/{{ username }}/Downloads'
    pos: 11
    view: grid
    display: folder
    sort: name
    sections: other