---
#### Some base setup including ssh keys
#
# ssh_key_name is in defaults
#
####
- name: Check hostname
  command: hostname
  register: current_hostname
  changed_when: false

- name: Set computer name
  hostname:
    name: "{{ hostname }}"
  become: true
  when: current_hostname.stdout != hostname

- name: Defaults host name
  osx_defaults:
    domain: com.apple.smb.server
    key: NetBIOSName
    type: string
    value: "{{ hostname }}"
  become: true
  become_user: root

- name: Check if key exists
  stat:
    path: "{{ ssh_key_name }}"
  register: ssh_key

- name: Create ssh key(s)
  ansible.builtin.openssh_keypair:
    path: "{{ ssh_key_name }}"
    type: rsa
    size: 2048  # Optionally specify key size
  when: (ssh_key.stat.exists == false)
