---
- name: Set Git user name
  community.general.git_config:
    name: user.name
    value: "{{ username }}"
    scope: global
  tags: git

- name: Set Git user email
  community.general.git_config:
    name: user.email
    value: "{{ email }}"
    scope: global
  tags: git
