---
- name: Configure OSX Machines
  hosts: osx
  connection: local
  # become: true

  roles:
    - osx_base
    - cli
    - apps
    - defaults
    - git

  tasks:
    - name: Create dirs
      ansible.builtin.debug:
        var: "{{ create_dirs }}"
      tags:
        - osx_base
