---
#### Set up OSX machines
# Comment out any module you don't want, but
# beware dependencies of modules
####
- name: Set up osx host
  hosts: osx
  connection: local
  pre_tasks:
    - name: Find our variables
      include_vars: "{{ item }}"
      with_first_found:
        - "{{ inventory_dir }}/local.yml"
        - "{{ inventory_dir }}/defaults.yml"
      tags:
        - osx_base
        - dotfiles
        - homebrew
        - mas
        - pip
        - golang
        - github
        - defaults
        - vim-plug
        - wallpaper
  roles:
    - {role: 'osx_base', tags: 'osx_base'}
    - {role: 'dotfiles', tags: 'dotfiles', when: dotfiles}
    - {role: 'homebrew', tags: 'homebrew', when: homebrew}
    - {role: 'mas', tags: 'mas', when: mas}
    - {role: 'pip', tags: 'pip', when: pip_packages or pip3_packages}
    - {role: 'golang', tags: 'golang', when: go_packages}
    - {role: 'github', tags: 'github', when: github}
    - {role: 'defaults', tags: 'defaults', when: defaults}
    - {role: 'vim-plug', tags: 'vim-plug', when: vimplug}
    - {role: 'wallpaper', tags: 'wallpaper', when: wallpaper}
