---
- name: Ensure requirements
  ansible.builtin.package:
    name: zsh
    state: present
  tags: cli
  with_items: "{{ cli_role_reqs }}"

- name: Ensure iterm2 is installed
  ansible.builtin.homebrew_cask:
    name: iterm2
    state: present
  tags: cli

- name: Install oh-my-zsh
  block:
    - name: Check if Oh My Zsh is already installed
      ansible.builtin.stat:
        path: "{{ oh_my_zsh_path }}"
      register: oh_my_zsh_installed
      changed_when: false
      tags: cli

    - name: Install Oh My Zsh
      ansible.builtin.shell:
        cmd: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        creates: "{{ oh_my_zsh_path }}"
      when: not oh_my_zsh_installed.stat.exists
      tags: cli