---
# Main task list for the CLI role

- name: Execute install tasks
  import_tasks: install.yml
  tags: cli

- name: Execute plugin setup tasks
  import_tasks: plugins.yml
  tags: cli

- name: Execute theme setup tasks
  import_tasks: themes.yml
  tags: cli
